## default config
spring:
  profiles:
    active: dev
  aop:
    auto: true
    proxy-target-class: true
#  datasource:
#    name: dataSource
#    type: org.apache.tomcat.jdbc.pool.DataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    tomcat:
#      jdbc-interceptors: ConnectionState;StatementFinalizer
#      validation-query: select 1

logging:
  level:
    root: debug
  file: /data/log/ricky/ricky-service-log/ricky-service


  dubbo:
    application:
      name: ricky-service
    protocol:
      port: 20232
    registry1:
      address: zookeeper://zkserver1:2181
      file: /data/log/ricky/ricky-service-log/ricky-service-dubbo1.cache
  cache:
    address1: mmserver1:11211
    address2: mmserver2:11211
    revision:
      project-name: ricky
      delay: 10
#  active-mq:
#    queue-producer-service:
#      url:  failover:(tcp://mqserver1:61616)
#      queue-name: im_dev
#    queue-consumer-service:
#      url: failover:(tcp://mqserver1:61616)
#      queue-name: im_dev
#    topic-consumer-service:
#      queue-name: im_dev2
#      url: failover:(tcp://mqserver1:61616)
#    topic-producer-service:
#      queue-name: im_dev2
#      url: failover:(tcp://mqserver1:61616)

---
spring:
  profiles: dev
#  datasource:
#    url: jdbc:mysql://my.centos.com:3306/peppa
#    username: root
#    password: 123456

logging:
  file: ../../ricky-service

framework:
  dubbo:
    registry1:
      address: zookeeper://zkserver1:2181
      file: ../../ricky-service-dubbo1.cache
  cache:
    address1: mmserver1:11211
    address2: mmserver2:11211
#  active-mq:
#    queue-producer-service:
#      url:  failover:(tcp://172.16.11.44:61616)
#      queue-name: im_dev
#    queue-consumer-service:
#      url: failover:(tcp://172.16.11.44:61616)
#      queue-name: im_dev
#    topic-consumer-service:
#      queue-name: im_dev2
#      url: failover:(tcp://172.16.11.44:61616)
#    topic-producer-service:
#      queue-name: im_dev2
#      url: failover:(tcp://172.16.11.44:61616)

